---
version: 2
targets:
  cpanel:
    - path: /
      type: python
      python_version: python3.12
      entry_point: manage.py
      requirements_file: requirements.txt
      post_deploy:
        - python3.12 manage.py migrate
        - python3.12 manage.py collectstatic --noinput
