# Generated by Django 5.2.8 on 2025-11-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
