# Generated by Django 5.2.8 on 2026-02-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bid',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
