# Generated by Django 5.2.8 on 2026-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bid',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
